// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Connessione diretta (non pooled) per Migrate/CLI; il client a runtime
    // (lib/prisma.ts) usa invece DATABASE_URL (pooled) tramite l'adapter.
    url: process.env["DIRECT_URL"],
  },
});
